server:
  port: 8010
  servlet:
    context-path: /springcloud-user

spring:
  application:
    name: springcloud-user
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update


mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.liang.springclouduser.entity

eureka:
  client:
    service-url:
      defaultZone: http://eureka8001.com:8001/eureka,http://eureka8002.com:8002/eureka,http://eureka8003.com:8003/eureka
    register-with-eureka: true #注册到中心
    fetch-registry: false #获取注册中心注册信息
  instance:
    instance-id: user8010 #服务别名
    prefer-ip-address: true #显示ip地址
